# Query EcoDB from Python

Read-only examples against the `eco` schema (PostgreSQL / PostGIS).

Start the database first:

```bash
docker compose up -d
```

Install notebook dependencies once:

```bash
pip install -r notebooks/requirements.txt
```

Default connection (same as `etl/db.py` and the README):

| | |
|---|---|
| Host | `localhost` |
| Port | `5432` |
| Database | `eco_monitoring` |
| User / password | `eco` / `eco` |

Override with `PGHOST`, `PGPORT`, `PGUSER`, `PGPASSWORD`, `PGDATABASE` if needed.

In [13]:
import os

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

pd.set_option("display.max_columns", 40)
pd.set_option("display.max_rows", 50)
pd.set_option("display.width", 120)

url = URL.create(
    "postgresql+psycopg2",
    username=os.environ.get("PGUSER", "eco"),
    password=os.environ.get("PGPASSWORD", "eco"),
    host=os.environ.get("PGHOST", "localhost"),
    port=int(os.environ.get("PGPORT", "5432")),
    database=os.environ.get("PGDATABASE", "eco_monitoring"),
)
engine = create_engine(url, connect_args={"client_encoding": "UTF8"})


def read_sql(sql: str, **params) -> pd.DataFrame:
    return pd.read_sql(text(sql), engine, params=params or None)


read_sql("SELECT current_database() AS db, current_user AS user, version() AS version")

               db user                                            version
0  eco_monitoring  eco  PostgreSQL 14.13 (Debian 14.13-1.pgdg110+1) on...

## Schema objects

Tables and ArcGIS Query Layer views in `eco`.

In [14]:
read_sql(
    """
    SELECT
        n.nspname AS schema,
        c.relname AS name,
        CASE c.relkind
            WHEN 'r' THEN 'table'
            WHEN 'v' THEN 'view'
            ELSE c.relkind::text
        END AS kind
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'eco'
      AND c.relkind IN ('r', 'v')
    ORDER BY kind, name
    """
)

   schema                    name   kind
0     eco             attachments  table
1     eco      field_measurements  table
2     eco     guideline_standards  table
3     eco        guideline_values  table
4     eco            laboratories  table
5     eco       monitoring_points  table
6     eco       parameter_aliases  table
7     eco              parameters  table
8     eco           point_aliases  table
9     eco             qa_findings  table
10    eco                qa_rules  table
11    eco                 qa_runs  table
12    eco          qa_spot_checks  table
13    eco         ref_media_types  table
14    eco            ref_qc_codes  table
15    eco      result_exceedances  table
16    eco                 results  table
17    eco                 samples  table
18    eco         sampling_events  table
19    eco       schema_migrations  table
20    eco                   sites  table
21    eco      staging_lab_import  table
22    eco            water_levels  table
23    eco  vw_exceedances_summary   view
24    eco       vw_latest_results   view
25    eco         vw_results_flat   view
26    eco         vw_water_levels   view

## Catalogs: sites, points, parameters

In [3]:
sites = read_sql(
    """
    SELECT site_id, site_code, name_ru, region, is_active
    FROM eco.sites
    ORDER BY site_code
    """
)
sites

   site_id site_code                     name_ru                          region  is_active
0        4       OSK  Усть-Каменогорск (Оскемен)  Восточно-Казахстанская область       True

In [15]:
points = read_sql(
    """
    SELECT
        p.point_id,
        p.point_code,
        p.name_ru,
        s.site_code,
        p.media_type,
        ST_Y(p.geom) AS lat,
        ST_X(p.geom) AS lon,
        p.is_active
    FROM eco.monitoring_points p
    JOIN eco.sites s ON s.site_id = p.site_id
    ORDER BY p.media_type, p.point_code
    """
)
points.head(15)

    point_id point_code                   name_ru site_code media_type   lat   lon  is_active
0          4        Т-1   Точка Т-1 (граница СЗЗ)       OSK        air  None  None       True
1         13       Т-10  Точка Т-10 (граница СЗЗ)       OSK        air  None  None       True
2         14       Т-11  Точка Т-11 (граница СЗЗ)       OSK        air  None  None       True
3         15       Т-12  Точка Т-12 (граница СЗЗ)       OSK        air  None  None       True
4         16       Т-13  Точка Т-13 (граница СЗЗ)       OSK        air  None  None       True
5         17       Т-14  Точка Т-14 (граница СЗЗ)       OSK        air  None  None       True
6         18       Т-15  Точка Т-15 (граница СЗЗ)       OSK        air  None  None       True
7         19       Т-16  Точка Т-16 (граница СЗЗ)       OSK        air  None  None       True
8         20       Т-17  Точка Т-17 (граница СЗЗ)       OSK        air  None  None       True
9         21       Т-18  Точка Т-18 (граница СЗЗ)       OSK        air  None  None       True
10        22       Т-19  Точка Т-19 (граница СЗЗ)       OSK        air  None  None       True
11         5        Т-2   Точка Т-2 (граница СЗЗ)       OSK        air  None  None       True
12        23       Т-20  Точка Т-20 (граница СЗЗ)       OSK        air  None  None       True
13        24       Т-21  Точка Т-21 (граница СЗЗ)       OSK        air  None  None       True
14        25       Т-22  Точка Т-22 (граница СЗЗ)       OSK        air  None  None       True

In [16]:
parameters = read_sql(
    """
    SELECT param_id, param_code, name_ru, name_en, unit, media_type
    FROM eco.parameters
    ORDER BY media_type NULLS LAST, param_code
    """
)
parameters

    param_id param_code                name_ru                 name_en       unit     media_type
0          5         CO         Углерода оксид         Carbon monoxide      mg/m3            air
1          4       Dust    Пыль неорганическая          Inorganic dust      mg/m3            air
2          8        HCN      Цианистый водород        Hydrogen cyanide      mg/m3            air
3          6        NO2          Азота диоксид        Nitrogen dioxide      mg/m3            air
4          7        SO2           Сера диоксид          Sulfur dioxide      mg/m3            air
5         21         As                 Мышьяк                 Arsenic     mg/dm3  surface_water
6         26       BOD5                   БПК5                    BOD5     mg/dm3  surface_water
7         10         CN                Цианиды                Cyanides     mg/dm3  surface_water
8         14        CNS               Роданиды            Thiocyanates     mg/dm3  surface_water
9         11    CN_FREE        Цианиды простые           Free cyanides     mg/dm3  surface_water
10        12     CN_TOT          Цианиды общие          Total cyanides     mg/dm3  surface_water
11        13     CN_WAD            Цианиды WAD            WAD cyanides     mg/dm3  surface_water
12        25        COD                    ХПК                     COD     mg/dm3  surface_water
13        18         Ca                Кальций                 Calcium     mg/dm3  surface_water
14        33         Cd                 Кадмий                 Cadmium     mg/dm3  surface_water
15        22         Cl                Хлориды               Chlorides     mg/dm3  surface_water
16        34         Cr                   Хром                Chromium     mg/dm3  surface_water
17        32         Cu                   Медь                  Copper     mg/dm3  surface_water
18        82         DO  Растворенный кислород        Dissolved oxygen     mg/dm3  surface_water
19        17         Fe           Железо общее              Total iron     mg/dm3  surface_water
20        20      HARDN        Жесткость общая          Total hardness  mg-eq/dm3  surface_water
21        16       HCO3         Гидрокарбонаты            Bicarbonates     mg/dm3  surface_water
22        80         Hg                  Ртуть                 Mercury     mg/dm3  surface_water
23        19         Mg                 Магний               Magnesium     mg/dm3  surface_water
24        35         Mn               Марганец               Manganese     mg/dm3  surface_water
25        28        NH4        Азот аммонийный       Ammonium nitrogen     mg/dm3  surface_water
26        27        NO3          Азот нитратов        Nitrate nitrogen     mg/dm3  surface_water
27        36         Ni                 Никель                  Nickel     mg/dm3  surface_water
28        31        OIL          Нефтепродукты      Petroleum products     mg/dm3  surface_water
29         9         PH                     рН                      pH         pH  surface_water
30        29        PO4                Фосфаты              Phosphates     mg/dm3  surface_water
31        37         Pb                 Свинец                    Lead     mg/dm3  surface_water
32        15        SO4               Сульфаты                Sulfates     mg/dm3  surface_water
33        24         SS    Взвешенные вещества        Suspended solids     mg/dm3  surface_water
34        30       SURF                    ПАВ             Surfactants     mg/dm3  surface_water
35        41      S_TOT             Сера общая            Total sulfur     mg/dm3  surface_water
36        38         Sb                 Сурьма                Antimony     mg/dm3  surface_water
37        39         Se                  Селен                Selenium     mg/dm3  surface_water
38        23        TDS          Сухой остаток  Total dissolved solids     mg/dm3  surface_water
39        81         Te                 Теллур               Tellurium     mg/dm3  surface_water
40        40         Zn                   Цинк                    Zinc     mg/dm3  surface_water

## Lab results

`eco.vw_results_flat` is one row per lab result (the same layer used in ArcGIS).
Geometry is omitted here; use `ST_X` / `ST_Y` if you need coordinates.

In [17]:
results = read_sql(
    """
    SELECT
        event_date,
        site_code,
        point_code,
        media_type,
        param_code,
        param_name_ru,
        result_value,
        less_than,
        unit,
        qc_code,
        has_exceedance,
        max_exceedance_ratio
    FROM eco.vw_results_flat
    ORDER BY event_date DESC, point_code, param_code
    LIMIT 20
    """
)
results

,event_date,site_code,point_code,media_type,param_code,param_name_ru,result_value,less_than,unit,qc_code,has_exceedance,max_exceedance_ratio
0,2025-11-18,OSK,Т-1,air,CO,Углерода оксид,2.4600,False,mg/m3,A,False,None
1,2025-11-18,OSK,Т-1,air,Dust,Пыль неорганическая,0.0822,False,mg/m3,A,False,None
2,2025-11-18,OSK,Т-1,air,HCN,Цианистый водород,0.0100,True,mg/m3,R,False,None
3,2025-11-18,OSK,Т-1,air,NO2,Азота диоксид,0.0734,False,mg/m3,A,False,None
4,2025-11-18,OSK,Т-1,air,SO2,Сера диоксид,0.0615,False,mg/m3,A,False,None
5,2025-11-18,OSK,Т-10,air,CO,Углерода оксид,2.7400,False,mg/m3,A,False,None
6,2025-11-18,OSK,Т-10,air,Dust,Пыль неорганическая,0.0745,False,mg/m3,C,False,None
7,2025-11-18,OSK,Т-10,air,HCN,Цианистый водород,0.0100,True,mg/m3,R,False,None
8,2025-11-18,OSK,Т-10,air,NO2,Азота диоксид,0.0851,False,mg/m3,A,False,None
9,2025-11-18,OSK,Т-10,air,SO2,Сера диоксид,0.0722,False,mg/m3,A,False,None
10,2025-11-18,OSK,Т-11,air,CO,Углерода оксид,1.9700,False,mg/m3,A,False,None
11,2025-11-18,OSK,Т-11,air,Dust,Пыль неорганическая,0.0563,False,mg/m3,A,False,None
12,2025-11-18,OSK,Т-11,air,HCN,Цианистый водород,0.0100,True,mg/m3,R,False,None
13,2025-11-18,OSK,Т-11,air,NO2,Азота диоксид,0.0752,False,mg/m3,A,False,None
14,2025-11-18,OSK,Т-11,air,SO2,Сера диоксид,0.0607,False,mg/m3,A,False,None
15,2025-11-18,OSK,Т-12,air,CO,Углерода оксид,2.5500,False,mg/m3,A,False,None
16,2025-11-18,OSK,Т-12,air,Dust,Пыль неорганическая,0.0701,False,mg/m3,A,False,None
17,2025-11-18,OSK,Т-12,air,HCN,Цианистый водород,0.0100,True,mg/m3,R,False,None
18,2025-11-18,OSK,Т-12,air,NO2,Азота диоксид,0.0769,False,mg/m3,A,False,None
19,2025-11-18,OSK,Т-12,air,SO2,Сера диоксид,0.0583,False,mg/m3,A,False,None

In [7]:
summary = read_sql(
    """
    SELECT
        media_type,
        param_code,
        count(*) AS n_results,
        count(*) FILTER (WHERE less_than) AS n_non_detect,
        count(*) FILTER (WHERE has_exceedance) AS n_exceedance,
        min(event_date) AS first_date,
        max(event_date) AS last_date
    FROM eco.vw_results_flat
    GROUP BY media_type, param_code
    ORDER BY media_type, param_code
    """
)
summary

  media_type param_code  n_results  n_non_detect  n_exceedance  first_date   last_date
0        air         CO        432             0             0  2020-03-17  2025-11-18
1        air       Dust        720             0             1  2020-03-17  2025-11-18
2        air        HCN        720           720             0  2020-03-17  2025-11-18
3        air        NO2        432             0             0  2020-03-17  2025-11-18
4        air        SO2        432             0             0  2020-03-17  2025-11-18

## Exceedances and latest values

- `vw_exceedances_summary` — one row per result × guideline
- `vw_latest_results` — latest result per (point, parameter); QC codes `D` and `R` are excluded

In [8]:
exceedances = read_sql(
    """
    SELECT
        event_date,
        point_code,
        param_code,
        param_name_ru,
        result_value,
        unit,
        standard_code,
        limit_value_applied,
        ratio,
        exceedance_pct
    FROM eco.vw_exceedances_summary
    ORDER BY ratio DESC
    """
)
exceedances

,event_date,point_code,param_code,param_name_ru,result_value,unit,standard_code,limit_value_applied,ratio,exceedance_pct
0,2020-03-17,Т-6,Dust,Пыль неорганическая,1.53,mg/m3,PDK_MR_AIR,0.3,5.1,410.0

In [9]:
latest = read_sql(
    """
    SELECT
        event_date,
        point_code,
        param_code,
        result_value,
        less_than,
        unit,
        has_exceedance
    FROM eco.vw_latest_results
    WHERE media_type = 'air'
    ORDER BY point_code, param_code
    """
)
latest.head(20)

    event_date point_code param_code  result_value  less_than   unit  has_exceedance
0   2025-11-18        Т-1         CO        2.4600      False  mg/m3           False
1   2025-11-18        Т-1       Dust        0.0822      False  mg/m3           False
2   2025-11-18        Т-1        HCN        0.0100       True  mg/m3           False
3   2025-11-18        Т-1        NO2        0.0734      False  mg/m3           False
4   2025-11-18        Т-1        SO2        0.0615      False  mg/m3           False
5   2025-11-18       Т-10         CO        2.7400      False  mg/m3           False
6   2025-11-18       Т-10       Dust        0.0745      False  mg/m3           False
7   2025-11-18       Т-10        HCN        0.0100       True  mg/m3           False
8   2025-11-18       Т-10        NO2        0.0851      False  mg/m3           False
9   2025-11-18       Т-10        SO2        0.0722      False  mg/m3           False
10  2025-11-18       Т-11         CO        1.9700      False  mg/m3           False
11  2025-11-18       Т-11       Dust        0.0563      False  mg/m3           False
12  2025-11-18       Т-11        HCN        0.0100       True  mg/m3           False
13  2025-11-18       Т-11        NO2        0.0752      False  mg/m3           False
14  2025-11-18       Т-11        SO2        0.0607      False  mg/m3           False
15  2025-11-18       Т-12         CO        2.5500      False  mg/m3           False
16  2025-11-18       Т-12       Dust        0.0701      False  mg/m3           False
17  2025-11-18       Т-12        HCN        0.0100       True  mg/m3           False
18  2025-11-18       Т-12        NO2        0.0769      False  mg/m3           False
19  2025-11-18       Т-12        SO2        0.0583      False  mg/m3           False

## Filter by parameter

Change `PARAM` to `CO`, `Dust`, `HCN`, `NO2`, or `SO2`.

In [10]:
PARAM = "SO2"

series = read_sql(
    """
    SELECT
        event_date,
        point_code,
        result_value,
        less_than,
        unit,
        has_exceedance
    FROM eco.vw_results_flat
    WHERE param_code = :param
    ORDER BY event_date, point_code
    """,
    param=PARAM,
)
series

     event_date point_code  result_value  less_than   unit  has_exceedance
0    2020-03-17        Т-1        0.0230      False  mg/m3           False
1    2020-03-17       Т-10        0.0490      False  mg/m3           False
2    2020-03-17       Т-11        0.0230      False  mg/m3           False
3    2020-03-17       Т-12        0.0360      False  mg/m3           False
4    2020-03-17       Т-13        0.0340      False  mg/m3           False
..          ...        ...           ...        ...    ...             ...
427  2025-11-18        Т-5        0.0531      False  mg/m3           False
428  2025-11-18        Т-6        0.0593      False  mg/m3           False
429  2025-11-18        Т-7        0.0538      False  mg/m3           False
430  2025-11-18        Т-8        0.0677      False  mg/m3           False
431  2025-11-18        Т-9        0.0682      False  mg/m3           False

[432 rows x 6 columns]

## Query with type of analysis

Edit the SQL below. Use `:name` placeholders and pass them as keyword arguments to `read_sql`.

In [12]:
df = read_sql(
    """
    SELECT *
    FROM eco.vw_results_flat
    WHERE media_type = :media
    LIMIT 5
    """,
    media="air",
)
df

,objectid,result_id,sample_id,event_id,site_id,site_code,site_name_ru,point_id,point_code,point_name_ru,media_type,geom,lab_id,lab_code,lab_name_ru,sample_code,coc_number,event_date,collection_datetime,param_id,param_code,param_name_ru,param_name_en,unit,result_value,less_than,mdl,qc_code,lab_method,analysis_datetime,has_exceedance,max_exceedance_ratio,comments,created_at
0,10,10,7,10,4,OSK,Усть-Каменогорск (Оскемен),4,Т-1,Точка Т-1 (граница СЗЗ),air,None,4,PEK,Производственный экологический контроль,None,None,2020-03-17,2020-03-17 00:00:00+00:00,4,Dust,Пыль неорганическая,Inorganic dust,mg/m3,0.125,False,0.01,C,None,None,False,None,None,2026-09-09 17:14:24.710709+00:00
1,40,40,7,10,4,OSK,Усть-Каменогорск (Оскемен),4,Т-1,Точка Т-1 (граница СЗЗ),air,None,4,PEK,Производственный экологический контроль,None,None,2020-03-17,2020-03-17 00:00:00+00:00,5,CO,Углерода оксид,Carbon monoxide,mg/m3,2.210,False,0.10,C,None,None,False,None,None,2026-09-09 17:14:24.710709+00:00
2,58,58,7,10,4,OSK,Усть-Каменогорск (Оскемен),4,Т-1,Точка Т-1 (граница СЗЗ),air,None,4,PEK,Производственный экологический контроль,None,None,2020-03-17,2020-03-17 00:00:00+00:00,6,NO2,Азота диоксид,Nitrogen dioxide,mg/m3,0.074,False,0.01,C,None,None,False,None,None,2026-09-09 17:14:24.710709+00:00
3,76,76,7,10,4,OSK,Усть-Каменогорск (Оскемен),4,Т-1,Точка Т-1 (граница СЗЗ),air,None,4,PEK,Производственный экологический контроль,None,None,2020-03-17,2020-03-17 00:00:00+00:00,7,SO2,Сера диоксид,Sulfur dioxide,mg/m3,0.023,False,0.01,C,None,None,False,None,None,2026-09-09 17:14:24.710709+00:00
4,94,94,7,10,4,OSK,Усть-Каменогорск (Оскемен),4,Т-1,Точка Т-1 (граница СЗЗ),air,None,4,PEK,Производственный экологический контроль,None,None,2020-03-17,2020-03-17 00:00:00+00:00,8,HCN,Цианистый водород,Hydrogen cyanide,mg/m3,0.010,True,0.01,B,None,None,False,None,None,2026-09-09 17:14:24.710709+00:00